// 'use client'

import NavHeader from "@/components/NavHeader";
import { Figtree, Shantell_Sans } from "next/font/google";
import "./globals.css";

const shantell = Shantell_Sans({ subsets: ["latin"], weights: 400 });
const figtree = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 
  return (
    <html lang='en'>
      <body className={shantell.className}>
        <div className={figtree.className}>
          <NavHeader />
        </div>
        {children}
      </body>
    </html>
  );
}
